# theme = "jetbrains_dark"
theme = "nord-night"

[editor]
line-number = "relative"
color-modes = true
true-color = true
bufferline = "multiple"
text-width = 120

[keys.normal]

[keys.insert]
"A-q" = "normal_mode"

