# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2f9b1996-87bb-4d42-9acb-80cb1543b4a5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-facb725f-b7ed-4dce-b2d3-1831ee71cd12".device = "/dev/disk/by-uuid/facb725f-b7ed-4dce-b2d3-1831ee71cd12";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5FE2-7C5E";
      fsType = "vfat";
    };

  swapDevices =
    [ 
    # { device = "/dev/disk/by-uuid/c77e058f-d6ab-4bb4-9be3-8896b67e8966"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
